fixtures:
  symlinks:
    nginx: "#{source_dir}"
  repositories:
    pe_staging: "git@github.com:puppetlabs/puppetlabs-pe_staging.git"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
